/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './gmap';
import * as i2 from '@angular/common';
export const GMapModuleNgFactory:i0.NgModuleFactory<i1.GMapModule> = i0.ɵcmf(i1.GMapModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i2.CommonModule,
          i2.CommonModule,([] as any[])),i0.ɵmpd(512,i1.GMapModule,i1.GMapModule,([] as any[]))]);
    });
const styles_GMap:any[] = ([] as any[]);
export const RenderType_GMap:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_GMap,
    data:{}});
export function View_GMap_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'div',([] as any[]),
      [[8,'className',0]],(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(278528,(null as any),0,i2.NgStyle,[i0.KeyValueDiffers,i0.ElementRef,
          i0.Renderer],{ngStyle:[0,'ngStyle']},(null as any))],(_ck,_v) => {
    var _co:i1.GMap = _v.component;
    const currVal_1:any = _co.style;
    _ck(_v,1,0,currVal_1);
  },(_ck,_v) => {
    var _co:i1.GMap = _v.component;
    const currVal_0:any = _co.styleClass;
    _ck(_v,0,0,currVal_0);
  });
}
export function View_GMap_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'p-gmap',([] as any[]),
      (null as any),(null as any),(null as any),View_GMap_0,RenderType_GMap)),i0.ɵdid(8699904,
      (null as any),0,i1.GMap,[i0.ElementRef,i0.IterableDiffers,i0.ChangeDetectorRef,
          i0.NgZone],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const GMapNgFactory:i0.ComponentFactory<i1.GMap> = i0.ɵccf('p-gmap',i1.GMap,
    View_GMap_Host_0,{style:'style',styleClass:'styleClass',options:'options',overlays:'overlays'},
    {onMapClick:'onMapClick',onOverlayClick:'onOverlayClick',onOverlayDragStart:'onOverlayDragStart',
        onOverlayDrag:'onOverlayDrag',onOverlayDragEnd:'onOverlayDragEnd',onMapReady:'onMapReady',
        onMapDragEnd:'onMapDragEnd',onZoomChanged:'onZoomChanged'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3NvdXJhYmhzaW5naC9Eb2N1bWVudHMvTXlQcm9qZWN0cy9PcGVuIFNvdXJjZS91bHRpbWF0ZS1wcmltZU5nL3NyYy9hcHAvY29tcG9uZW50cy9nbWFwL2dtYXAubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvc291cmFiaHNpbmdoL0RvY3VtZW50cy9NeVByb2plY3RzL09wZW4gU291cmNlL3VsdGltYXRlLXByaW1lTmcvc3JjL2FwcC9jb21wb25lbnRzL2dtYXAvZ21hcC50cyIsIm5nOi8vL1VzZXJzL3NvdXJhYmhzaW5naC9Eb2N1bWVudHMvTXlQcm9qZWN0cy9PcGVuIFNvdXJjZS91bHRpbWF0ZS1wcmltZU5nL3NyYy9hcHAvY29tcG9uZW50cy9nbWFwL2dtYXAudHMuR01hcC5odG1sIiwibmc6Ly8vVXNlcnMvc291cmFiaHNpbmdoL0RvY3VtZW50cy9NeVByb2plY3RzL09wZW4gU291cmNlL3VsdGltYXRlLXByaW1lTmcvc3JjL2FwcC9jb21wb25lbnRzL2dtYXAvZ21hcC50cy5HTWFwX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBbbmdTdHlsZV09XCJzdHlsZVwiIFtjbGFzc109XCJzdHlsZUNsYXNzXCI+PC9kaXY+IiwiPHAtZ21hcD48L3AtZ21hcD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7YUFBQTtxQkFBQTs7SUFBSztJQUFMLFdBQUssU0FBTDs7O0lBQXVCO0lBQXZCLFdBQXVCLFNBQXZCOzs7O29CQ0FBO01BQUEsK0VBQUE7TUFBQTttQkFBQTtJQUFBOzs7Ozs7OyJ9
