/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './blockui';
import * as i2 from '@angular/common';
import * as i3 from '../dom/domhandler';
export const BlockUIModuleNgFactory:i0.NgModuleFactory<i1.BlockUIModule> = i0.ɵcmf(i1.BlockUIModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i2.CommonModule,
          i2.CommonModule,([] as any[])),i0.ɵmpd(512,i1.BlockUIModule,i1.BlockUIModule,
          ([] as any[]))]);
    });
const styles_BlockUI:any[] = ([] as any[]);
export const RenderType_BlockUI:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_BlockUI,
    data:{}});
export function View_BlockUI_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{mask:0}),(_l()(),i0.ɵted((null as any),['\n        '])),
      (_l()(),i0.ɵeld(0,[[1,0],['mask',1]],(null as any),7,'div',[['class','ui-blockui ui-widget-overlay']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(278528,(null as any),0,i2.NgClass,[i0.IterableDiffers,i0.KeyValueDiffers,
          i0.ElementRef,i0.Renderer],{klass:[0,'klass'],ngClass:[1,'ngClass']},(null as any)),
      i0.ɵpod({'ui-blockui-document':0}),i0.ɵdid(278528,(null as any),0,i2.NgStyle,
          [i0.KeyValueDiffers,i0.ElementRef,i0.Renderer],{ngStyle:[0,'ngStyle']},(null as any)),
      i0.ɵpod({display:0}),(_l()(),i0.ɵted((null as any),['\n            '])),i0.ɵncd((null as any),
          0),(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵted((null as any),
          ['\n    ']))],(_ck,_v) => {
    var _co:i1.BlockUI = _v.component;
    const currVal_0:any = 'ui-blockui ui-widget-overlay';
    const currVal_1:any = _ck(_v,4,0,!_co.target);
    _ck(_v,3,0,currVal_0,currVal_1);
    const currVal_2:any = _ck(_v,6,0,(_co.blocked? 'block': 'none'));
    _ck(_v,5,0,currVal_2);
  },(null as any));
}
export function View_BlockUI_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'p-blockUI',([] as any[]),
      (null as any),(null as any),(null as any),View_BlockUI_0,RenderType_BlockUI)),
      i0.ɵprd(512,(null as any),i3.DomHandler,i3.DomHandler,([] as any[])),i0.ɵdid(4374528,
          (null as any),0,i1.BlockUI,[i0.ElementRef,i3.DomHandler],(null as any),(null as any))],
      (null as any),(null as any));
}
export const BlockUINgFactory:i0.ComponentFactory<i1.BlockUI> = i0.ɵccf('p-blockUI',
    i1.BlockUI,View_BlockUI_Host_0,{target:'target',blocked:'blocked'},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3NvdXJhYmhzaW5naC9Eb2N1bWVudHMvTXlQcm9qZWN0cy9PcGVuIFNvdXJjZS91bHRpbWF0ZS1wcmltZU5nL3NyYy9hcHAvY29tcG9uZW50cy9ibG9ja3VpL2Jsb2NrdWkubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvc291cmFiaHNpbmdoL0RvY3VtZW50cy9NeVByb2plY3RzL09wZW4gU291cmNlL3VsdGltYXRlLXByaW1lTmcvc3JjL2FwcC9jb21wb25lbnRzL2Jsb2NrdWkvYmxvY2t1aS50cyIsIm5nOi8vL1VzZXJzL3NvdXJhYmhzaW5naC9Eb2N1bWVudHMvTXlQcm9qZWN0cy9PcGVuIFNvdXJjZS91bHRpbWF0ZS1wcmltZU5nL3NyYy9hcHAvY29tcG9uZW50cy9ibG9ja3VpL2Jsb2NrdWkudHMuQmxvY2tVSS5odG1sIiwibmc6Ly8vVXNlcnMvc291cmFiaHNpbmdoL0RvY3VtZW50cy9NeVByb2plY3RzL09wZW4gU291cmNlL3VsdGltYXRlLXByaW1lTmcvc3JjL2FwcC9jb21wb25lbnRzL2Jsb2NrdWkvYmxvY2t1aS50cy5CbG9ja1VJX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICAgIDxkaXYgI21hc2sgY2xhc3M9XCJ1aS1ibG9ja3VpIHVpLXdpZGdldC1vdmVybGF5XCIgW25nQ2xhc3NdPVwieyd1aS1ibG9ja3VpLWRvY3VtZW50JzohdGFyZ2V0fVwiIFtuZ1N0eWxlXT1cIntkaXNwbGF5OiBibG9ja2VkID8gJ2Jsb2NrJyA6ICdub25lJ31cIj5cbiAgICAgICAgICAgIDxuZy1jb250ZW50PjwvbmctY29udGVudD5cbiAgICAgICAgPC9kaXY+XG4gICAgIiwiPHAtYmxvY2tVST48L3AtYmxvY2tVST4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7a0RDQUE7TUFDUTtVQUFBO2FBQUE7bUNBQUE7YUFBZ0QsbUNBQWhEO1VBQUE7YUFBNEYsY0FBa0QsMERBQzFJO1VBQUEsR0FBeUIsK0NBQ3ZCO1VBQUE7O0lBRks7SUFBcUM7SUFBaEQsV0FBVyxVQUFxQyxTQUFoRDtJQUE0RjtJQUE1RixXQUE0RixTQUE1Rjs7OztvQkNEUjtNQUFBO2FBQUEscUVBQUE7VUFBQTs7OzsifQ==
