/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './toolbar';
import * as i2 from '@angular/common';
export const ToolbarModuleNgFactory:i0.NgModuleFactory<i1.ToolbarModule> = i0.ɵcmf(i1.ToolbarModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i2.CommonModule,
          i2.CommonModule,([] as any[])),i0.ɵmpd(512,i1.ToolbarModule,i1.ToolbarModule,
          ([] as any[]))]);
    });
const styles_Toolbar:any[] = ([] as any[]);
export const RenderType_Toolbar:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_Toolbar,
    data:{}});
export function View_Toolbar_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),5,'div',([] as any[]),(null as any),(null as any),
      (null as any),(null as any),(null as any))),i0.ɵdid(278528,(null as any),0,i2.NgClass,
      [i0.IterableDiffers,i0.KeyValueDiffers,i0.ElementRef,i0.Renderer],{klass:[0,
          'klass'],ngClass:[1,'ngClass']},(null as any)),i0.ɵdid(278528,(null as any),
      0,i2.NgStyle,[i0.KeyValueDiffers,i0.ElementRef,i0.Renderer],{ngStyle:[0,'ngStyle']},
      (null as any)),(_l()(),i0.ɵted((null as any),['\n            '])),i0.ɵncd((null as any),
      0),(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵted((null as any),
      ['\n    ']))],(_ck,_v) => {
    var _co:i1.Toolbar = _v.component;
    const currVal_0:any = _co.styleClass;
    const currVal_1:any = 'ui-toolbar ui-widget ui-widget-header ui-corner-all ui-helper-clearfix';
    _ck(_v,2,0,currVal_0,currVal_1);
    const currVal_2:any = _co.style;
    _ck(_v,3,0,currVal_2);
  },(null as any));
}
export function View_Toolbar_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'p-toolbar',([] as any[]),
      (null as any),(null as any),(null as any),View_Toolbar_0,RenderType_Toolbar)),
      i0.ɵdid(49152,(null as any),0,i1.Toolbar,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const ToolbarNgFactory:i0.ComponentFactory<i1.Toolbar> = i0.ɵccf('p-toolbar',
    i1.Toolbar,View_Toolbar_Host_0,{style:'style',styleClass:'styleClass'},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3NvdXJhYmhzaW5naC9Eb2N1bWVudHMvTXlQcm9qZWN0cy9PcGVuIFNvdXJjZS91bHRpbWF0ZS1wcmltZU5nL3NyYy9hcHAvY29tcG9uZW50cy90b29sYmFyL3Rvb2xiYXIubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvc291cmFiaHNpbmdoL0RvY3VtZW50cy9NeVByb2plY3RzL09wZW4gU291cmNlL3VsdGltYXRlLXByaW1lTmcvc3JjL2FwcC9jb21wb25lbnRzL3Rvb2xiYXIvdG9vbGJhci50cyIsIm5nOi8vL1VzZXJzL3NvdXJhYmhzaW5naC9Eb2N1bWVudHMvTXlQcm9qZWN0cy9PcGVuIFNvdXJjZS91bHRpbWF0ZS1wcmltZU5nL3NyYy9hcHAvY29tcG9uZW50cy90b29sYmFyL3Rvb2xiYXIudHMuVG9vbGJhci5odG1sIiwibmc6Ly8vVXNlcnMvc291cmFiaHNpbmdoL0RvY3VtZW50cy9NeVByb2plY3RzL09wZW4gU291cmNlL3VsdGltYXRlLXByaW1lTmcvc3JjL2FwcC9jb21wb25lbnRzL3Rvb2xiYXIvdG9vbGJhci50cy5Ub29sYmFyX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICAgIDxkaXYgW25nQ2xhc3NdPVwiJ3VpLXRvb2xiYXIgdWktd2lkZ2V0IHVpLXdpZGdldC1oZWFkZXIgdWktY29ybmVyLWFsbCB1aS1oZWxwZXItY2xlYXJmaXgnXCIgW25nU3R5bGVdPVwic3R5bGVcIiBbY2xhc3NdPVwic3R5bGVDbGFzc1wiPlxuICAgICAgICAgICAgPG5nLWNvbnRlbnQ+PC9uZy1jb250ZW50PlxuICAgICAgICA8L2Rpdj5cbiAgICAiLCI8cC10b29sYmFyPjwvcC10b29sYmFyPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLCtDQUNRO01BQUE7TUFBQSxtREFBQTtNQUFBO1VBQUEsc0RBQUE7TUFBQTtNQUFBLGVBQWlJLDBEQUM3SDtNQUFBLEdBQXlCLCtDQUN2QjtNQUFBOztJQUZzRztJQUF2RztJQUFMLFdBQTRHLFVBQXZHLFNBQUw7SUFBMEY7SUFBMUYsV0FBMEYsU0FBMUY7Ozs7b0JDRFI7TUFBQTthQUFBOzs7OyJ9
